import type { Service, PricingPackage, Testimonial, FAQItem, ServiceArea, Stat, NavItem } from "@/types";

export const BUSINESS = {
  name: "GAutoDetailing",
  tagline: "Premium Mobile Auto Detailing",
  phone: "(843) 555-0192",
  email: "info@gautodetailing.com",
  instagram: "https://instagram.com/ga_autodetailing7",
  instagramHandle: "@ga_autodetailing7",
  owner: "Irwinsito",
  serviceType: "Mobile — We Come to You",
  serviceAreas: ["Hardeeville, SC", "Bluffton, SC", "Hilton Head Island, SC", "Beaufort, SC"],
  address: "Serving the Lowcountry, SC",
  baseUrl: "https://gautodetailing.com",
};

export const NAV_ITEMS: NavItem[] = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  {
    label: "Services",
    href: "/services",
    children: [
      { label: "All Services", href: "/services" },
      { label: "Exterior Detailing", href: "/services#exterior" },
      { label: "Interior Detailing", href: "/services#interior" },
      { label: "Paint Protection", href: "/services#protection" },
      { label: "Specialty Services", href: "/services#specialty" },
    ],
  },
  { label: "Pricing", href: "/pricing" },
  { label: "Gallery", href: "/gallery" },
  { label: "Reviews", href: "/reviews" },
  { label: "FAQ", href: "/faq" },
  {
    label: "Service Areas",
    href: "/service-areas",
    children: [
      { label: "Hardeeville, SC", href: "/service-areas/hardeeville" },
      { label: "Bluffton, SC", href: "/service-areas/bluffton" },
      { label: "Hilton Head Island, SC", href: "/service-areas/hilton-head" },
      { label: "Beaufort, SC", href: "/service-areas/beaufort" },
    ],
  },
  { label: "Contact", href: "/contact" },
];

export const STATS: Stat[] = [
  { value: "500", label: "Vehicles Detailed", suffix: "+" },
  { value: "100", label: "Mobile Service", suffix: "%" },
  { value: "4.9", label: "Average Rating", suffix: "★" },
  { value: "48", label: "Hour Response", suffix: "hr" },
  { value: "4", label: "Cities Served" },
];

export const SERVICES: Service[] = [
  // PACKAGES
  {
    id: "exterior-detail",
    name: "Exterior Detail",
    description: "A thorough exterior cleaning that removes dirt, grime, and contaminants from every surface, leaving your vehicle gleaming.",
    duration: "1–2 hrs",
    icon: "Car",
    category: "packages",
    features: ["Hand wash & rinse", "Clay bar treatment", "Wheel & tire cleaning", "Window cleaning", "Tire dressing", "Door jamb wipe-down"],
    price: "From $89",
  },
  {
    id: "interior-detail",
    name: "Interior Detail",
    description: "A complete interior transformation — deep vacuuming, steam cleaning, leather care, and odor elimination.",
    duration: "2–3 hrs",
    icon: "Sofa",
    category: "packages",
    features: ["Deep vacuum", "Dashboard & console cleaning", "Leather cleaning & conditioning", "Window cleaning", "Odor treatment", "Cup holder & vent cleaning"],
    price: "From $99",
  },
  {
    id: "full-detail",
    name: "Full Detail",
    description: "The complete package — combining our thorough exterior and interior services for a showroom-quality result.",
    duration: "3–5 hrs",
    icon: "Star",
    category: "packages",
    popular: true,
    features: ["Complete exterior wash", "Interior deep clean", "Engine bay cleaning", "Ceramic spray protection", "Wax & polish", "Leather conditioning"],
    price: "From $199",
  },
  {
    id: "express-detail",
    name: "Express Detail",
    description: "A quick refresh that covers the essentials — perfect for maintaining a clean vehicle between full details.",
    duration: "45–60 min",
    icon: "Zap",
    category: "packages",
    features: ["Exterior hand wash", "Interior vacuum", "Window cleaning", "Tire dressing", "Quick wipe-down"],
    price: "From $59",
  },
  {
    id: "maintenance-detail",
    name: "Maintenance Detail",
    description: "Regular upkeep to keep your vehicle in pristine condition — ideal for monthly maintenance clients.",
    duration: "1–2 hrs",
    icon: "RefreshCw",
    category: "packages",
    features: ["Full exterior wash", "Interior vacuum & wipe", "Window cleaning", "Tire dressing", "Priority scheduling"],
    price: "From $79",
  },
  {
    id: "premium-detail",
    name: "Premium Detail",
    description: "An elevated detailing experience with premium products and extra attention to every detail of your vehicle.",
    duration: "4–6 hrs",
    icon: "Gem",
    category: "packages",
    popular: true,
    features: ["Full exterior detail", "Clay bar decontamination", "Paint sealant application", "Complete interior detail", "Steam cleaning", "Leather conditioning"],
    price: "From $279",
  },
  {
    id: "deluxe-detail",
    name: "Deluxe Detail",
    description: "Our most comprehensive detailing package — for those who demand perfection and nothing less.",
    duration: "5–7 hrs",
    icon: "Crown",
    category: "packages",
    features: ["Everything in Premium", "Hot water extraction", "Headliner cleaning", "Trunk detail", "Ceramic spray protection", "Engine bay detail"],
    price: "From $349",
  },
  {
    id: "complete-detail",
    name: "Complete Detail",
    description: "The ultimate detailing experience — every inch of your vehicle restored to showroom perfection.",
    duration: "6–8 hrs",
    icon: "Trophy",
    category: "packages",
    features: ["Full deluxe detail", "Ceramic spray coat", "Paint decontamination", "Plastic restoration", "Ozone odor treatment", "Before & after photos"],
    price: "From $449",
  },

  // EXTERIOR
  {
    id: "clay-bar",
    name: "Clay Bar Treatment",
    description: "Removes embedded contaminants from paint that washing alone cannot remove, creating a perfectly smooth surface.",
    duration: "1–2 hrs",
    icon: "Layers",
    category: "exterior",
    features: ["Removes bonded contaminants", "Smooth paint surface", "Pre-polish prep", "Safe for all paint types"],
    price: "From $49",
  },
  {
    id: "paint-decontamination",
    name: "Paint Decontamination",
    description: "Iron and chemical decontamination to remove brake dust, rail dust, and other embedded metal particles.",
    duration: "45 min",
    icon: "Shield",
    category: "exterior",
    features: ["Iron decontamination", "Chemical fallout removal", "Safe for clear coat", "Extends paint life"],
    price: "From $39",
  },
  {
    id: "bug-removal",
    name: "Bug Removal",
    description: "Safe and effective removal of bug splatter and road grime without damaging your vehicle's finish.",
    duration: "30 min",
    icon: "Bug",
    category: "exterior",
    features: ["Bug & tar removal", "Paint-safe solvents", "No scratching", "Streak-free finish"],
    price: "From $29",
  },
  {
    id: "tar-removal",
    name: "Tar Removal",
    description: "Professional-grade tar spot removal from paint, glass, and trim without leaving residue.",
    duration: "30 min",
    icon: "Droplets",
    category: "exterior",
    features: ["Road tar removal", "Paint-safe products", "Trim & glass safe", "No residue"],
    price: "From $29",
  },
  {
    id: "engine-bay",
    name: "Engine Bay Cleaning",
    description: "Detailed engine bay cleaning and degreasing — making your engine bay as impressive as your exterior.",
    duration: "45–60 min",
    icon: "Settings",
    category: "exterior",
    features: ["Degreasing", "Steam cleaning", "Plastic dressing", "Safe electrical protection"],
    price: "From $49",
  },
  {
    id: "door-jamb",
    name: "Door Jamb Cleaning",
    description: "The often-overlooked door jambs cleaned and dressed to perfection — the mark of a true detail.",
    duration: "20 min",
    icon: "DoorOpen",
    category: "exterior",
    features: ["All jambs cleaned", "Rubber seal treatment", "Degreasing", "Streak-free"],
    price: "From $19",
  },
  {
    id: "window-cleaning",
    name: "Window Cleaning",
    description: "Crystal-clear windows inside and out, using professional glass cleaner for a streak-free finish.",
    duration: "20–30 min",
    icon: "Sparkles",
    category: "exterior",
    features: ["Interior & exterior glass", "Streak-free formula", "Film removal", "Rain repellent option"],
    price: "From $25",
  },
  {
    id: "glass-polishing",
    name: "Glass Polishing",
    description: "Remove light scratches, haze, and wiper marks from glass using professional glass polish compounds.",
    duration: "45–60 min",
    icon: "Eye",
    category: "exterior",
    features: ["Scratch reduction", "Haze removal", "Water spot removal", "Improved clarity"],
    price: "From $59",
  },
  {
    id: "mirror-cleaning",
    name: "Mirror Cleaning",
    description: "All mirrors thoroughly cleaned and polished for maximum visibility and aesthetics.",
    duration: "10 min",
    icon: "Scan",
    category: "exterior",
    features: ["All mirrors", "Streak-free", "Spot removal", "Included in most packages"],
    price: "Add-on",
  },

  // WHEEL & TIRE
  {
    id: "wheel-cleaning",
    name: "Wheel Cleaning",
    description: "Deep cleaning of all four wheels, removing brake dust, grime, and road contaminants.",
    duration: "30 min",
    icon: "Circle",
    category: "wheel-tire",
    features: ["All 4 wheels", "Brake dust removal", "Spoke cleaning", "Wheel well rinse"],
    price: "From $29",
  },
  {
    id: "wheel-decontamination",
    name: "Wheel Decontamination",
    description: "Iron and chemical decontamination for wheels — removes embedded brake dust and metal particles.",
    duration: "30 min",
    icon: "CircleDot",
    category: "wheel-tire",
    features: ["Iron decontamination", "Acid-free safe formula", "All wheel finishes", "Prevents corrosion"],
    price: "From $35",
  },
  {
    id: "wheel-protection",
    name: "Wheel Protection",
    description: "Sealant or wax application to protect wheel finish and make future cleaning easier.",
    duration: "30 min",
    icon: "ShieldCheck",
    category: "wheel-tire",
    features: ["Protection coating", "Repels brake dust", "Easier cleaning", "Long-lasting"],
    price: "From $29",
  },
  {
    id: "tire-cleaning",
    name: "Tire Cleaning",
    description: "Professional tire cleaning to remove brown-out, oxidation, and road grime from sidewalls.",
    duration: "15 min",
    icon: "CircleOff",
    category: "wheel-tire",
    features: ["Sidewall scrubbing", "Brown-out removal", "All tire sizes", "Deep clean"],
    price: "From $19",
  },
  {
    id: "tire-dressing",
    name: "Tire Dressing",
    description: "Premium tire dressing application for a deep black, long-lasting finish that resists brown-out.",
    duration: "15 min",
    icon: "Paintbrush",
    category: "wheel-tire",
    features: ["Premium tire shine", "UV protection", "Anti-brown-out", "Natural look option"],
    price: "From $19",
  },

  // INTERIOR
  {
    id: "vacuum",
    name: "Vacuum",
    description: "Thorough vacuuming of all carpet, seats, and crevices throughout the interior.",
    duration: "20–30 min",
    icon: "Minus",
    category: "interior",
    features: ["All carpet areas", "Seat vacuuming", "Crevice tools", "Trunk area"],
    price: "From $25",
  },
  {
    id: "deep-vacuum",
    name: "Deep Vacuum",
    description: "Intensive vacuuming with seat removal (where possible) and detailed crevice extraction.",
    duration: "45–60 min",
    icon: "ArrowDown",
    category: "interior",
    features: ["Seat removal option", "Under-seat cleaning", "All vents & crevices", "Pet hair extraction"],
    price: "From $45",
  },
  {
    id: "steam-cleaning",
    name: "Steam Cleaning",
    description: "High-temperature steam cleaning sanitizes and deep-cleans all interior surfaces naturally.",
    duration: "1–2 hrs",
    icon: "Flame",
    category: "interior",
    features: ["Kills 99.9% bacteria", "Chemical-free option", "Dashboard & console", "Safe for electronics"],
    price: "From $79",
  },
  {
    id: "hot-water-extraction",
    name: "Hot Water Extraction",
    description: "Professional-grade hot water extraction — the gold standard for carpet and upholstery deep cleaning.",
    duration: "1–2 hrs",
    icon: "Waves",
    category: "interior",
    features: ["Deep carpet cleaning", "Upholstery extraction", "Stain penetration", "Fast dry process"],
    price: "From $99",
  },
  {
    id: "carpet-shampoo",
    name: "Carpet Shampoo",
    description: "Complete carpet shampooing with professional agitation and extraction for spotless results.",
    duration: "1–2 hrs",
    icon: "Grid",
    category: "interior",
    features: ["Full carpet treatment", "Pre-treatment spray", "Agitation & extraction", "Odor neutralizer"],
    price: "From $89",
  },
  {
    id: "seat-shampoo",
    name: "Seat Shampoo",
    description: "Deep fabric seat shampooing to remove stains, odors, and embedded dirt from seat upholstery.",
    duration: "1 hr",
    icon: "Armchair",
    category: "interior",
    features: ["All fabric seats", "Stain pre-treatment", "Deep agitation", "Deodorizing"],
    price: "From $79",
  },
  {
    id: "leather-cleaning",
    name: "Leather Cleaning",
    description: "Professional pH-balanced leather cleaning to safely remove dirt and grime from all leather surfaces.",
    duration: "45 min",
    icon: "BookOpen",
    category: "interior",
    features: ["All leather surfaces", "pH balanced formula", "Crack prevention", "Color safe"],
    price: "From $49",
  },
  {
    id: "leather-conditioning",
    name: "Leather Conditioning",
    description: "Premium leather conditioner application to restore suppleness, prevent cracking, and protect leather.",
    duration: "30 min",
    icon: "Heart",
    category: "interior",
    features: ["Premium conditioner", "UV protection", "Crack prevention", "Restores luster"],
    price: "From $39",
  },
  {
    id: "plastic-restoration",
    name: "Plastic Restoration",
    description: "Restore faded interior and exterior plastic trim to a deep, rich black finish.",
    duration: "30–45 min",
    icon: "RefreshCcw",
    category: "interior",
    features: ["Faded plastic restored", "Long-lasting finish", "Interior & exterior", "UV protection"],
    price: "From $49",
  },
  {
    id: "dashboard-cleaning",
    name: "Dashboard Cleaning",
    description: "Complete dashboard cleaning, dusting, and dressing for a clean, protected finish.",
    duration: "20 min",
    icon: "LayoutDashboard",
    category: "interior",
    features: ["Dust removal", "Vent cleaning", "Gauge cluster", "UV protection dressing"],
    price: "From $25",
  },
  {
    id: "console-cleaning",
    name: "Console Cleaning",
    description: "Center console, gear shift area, and armrest cleaned and sanitized thoroughly.",
    duration: "20 min",
    icon: "Box",
    category: "interior",
    features: ["Center console", "Gear shift area", "Armrest", "Sanitizing treatment"],
    price: "From $20",
  },
  {
    id: "cup-holder-cleaning",
    name: "Cup Holder Cleaning",
    description: "Deep cleaning of cup holders and small compartments — the dirtiest places in your car.",
    duration: "15 min",
    icon: "Coffee",
    category: "interior",
    features: ["Steam extraction", "All cup holders", "Small compartments", "Sanitizing"],
    price: "From $15",
  },
  {
    id: "pet-hair-removal",
    name: "Pet Hair Removal",
    description: "Specialized tools and techniques to remove embedded pet hair from carpet and upholstery.",
    duration: "1–2 hrs",
    icon: "Scissors",
    category: "interior",
    features: ["Rubber brush tools", "All surfaces", "Vacuum extraction", "Filter cleaned"],
    price: "From $59",
  },
  {
    id: "odor-removal",
    name: "Odor Removal",
    description: "Eliminate cigarette smoke, pet odors, food smells, and musty odors with professional treatment.",
    duration: "1–2 hrs",
    icon: "Wind",
    category: "interior",
    features: ["Ozone treatment", "Odor neutralizer", "Source removal", "Lasting freshness"],
    price: "From $79",
  },
  {
    id: "stain-removal",
    name: "Stain Removal",
    description: "Targeted stain treatment for coffee, juice, ink, grease, and other tough stains.",
    duration: "30–60 min",
    icon: "Eraser",
    category: "interior",
    features: ["Spot treatment", "Multiple stain types", "Safe for upholstery", "Pre-inspection"],
    price: "From $35",
  },
  {
    id: "headliner-cleaning",
    name: "Headliner Cleaning",
    description: "Delicate yet thorough headliner cleaning to remove stains and discoloration safely.",
    duration: "30–45 min",
    icon: "AlignTop",
    category: "interior",
    features: ["Gentle technique", "Stain removal", "No saturation", "Color restoration"],
    price: "From $49",
  },
  {
    id: "trunk-cleaning",
    name: "Trunk Cleaning",
    description: "Complete trunk cleaning including carpet, spare tire area, and cargo space.",
    duration: "30 min",
    icon: "Package",
    category: "interior",
    features: ["Carpet cleaning", "Spare tire area", "Side panels", "Deodorizing"],
    price: "From $35",
  },

  // PROTECTION
  {
    id: "ceramic-spray",
    name: "Ceramic Spray Protection",
    description: "Professional-grade ceramic spray coating that provides hydrophobic protection and brilliant shine for months.",
    duration: "1 hr",
    icon: "Zap",
    category: "protection",
    popular: true,
    features: ["Hydrophobic coating", "UV protection", "3–6 month durability", "Mirror-like shine"],
    price: "From $99",
  },
  {
    id: "paint-sealant",
    name: "Paint Sealant",
    description: "Synthetic polymer paint sealant for superior paint protection and long-lasting gloss.",
    duration: "45 min",
    icon: "ShieldPlus",
    category: "protection",
    features: ["Polymer protection", "6–12 month durability", "High gloss finish", "UV & chemical resistance"],
    price: "From $79",
  },
  {
    id: "wax-protection",
    name: "Wax Protection",
    description: "Premium carnauba wax application for a warm, deep shine and paint protection.",
    duration: "45 min",
    icon: "Sun",
    category: "protection",
    features: ["Carnauba wax", "Deep warm shine", "Paint protection", "2–3 month durability"],
    price: "From $59",
  },

  // SPECIALTY
  {
    id: "suv-detailing",
    name: "SUV Detailing",
    description: "Specialized detailing tailored for the size and features of SUVs and crossovers.",
    duration: "3–6 hrs",
    icon: "Truck",
    category: "specialty",
    features: ["Third-row cleaning", "Larger surface coverage", "Cargo area detail", "Running boards"],
    price: "From $249",
  },
  {
    id: "truck-detailing",
    name: "Truck Detailing",
    description: "Full detailing for pickup trucks — cab, bed, and all exterior surfaces.",
    duration: "3–6 hrs",
    icon: "TruckIcon",
    category: "specialty",
    features: ["Cab interior detail", "Bed cleaning & liner care", "Running boards", "Exterior full detail"],
    price: "From $249",
  },
  {
    id: "luxury-vehicle",
    name: "Luxury Vehicle Detailing",
    description: "White-glove detailing service for exotic, luxury, and high-value vehicles using only top-tier products.",
    duration: "5–8 hrs",
    icon: "Diamond",
    category: "specialty",
    popular: true,
    features: ["Premium products only", "White-glove service", "Paint protection", "Concierge scheduling"],
    price: "From $399",
  },
  {
    id: "sports-car",
    name: "Sports Car Detailing",
    description: "Precision detailing for sports cars and performance vehicles with special attention to aerodynamic surfaces.",
    duration: "4–7 hrs",
    icon: "Gauge",
    category: "specialty",
    features: ["Low-profile care", "Brake caliper cleaning", "Performance wheel detail", "Carbon fiber care"],
    price: "From $349",
  },
  {
    id: "fleet-detailing",
    name: "Fleet Vehicle Detailing",
    description: "Professional fleet detailing programs for businesses — keep your company vehicles immaculate.",
    duration: "Custom",
    icon: "Building",
    category: "specialty",
    features: ["Volume pricing", "Flexible scheduling", "Branded report cards", "Monthly programs"],
    price: "Custom Quote",
  },
  {
    id: "motorcycle-detailing",
    name: "Motorcycle Detailing",
    description: "Complete motorcycle detailing — frame, chrome, tank, and wheels restored to show quality.",
    duration: "2–3 hrs",
    icon: "Bike",
    category: "specialty",
    features: ["Frame & tank polish", "Chrome restoration", "Wheel cleaning", "Chain lubrication"],
    price: "From $129",
  },
];

export const PRICING_PACKAGES: PricingPackage[] = [
  {
    id: "basic",
    name: "Basic Package",
    tagline: "The Essential Refresh",
    price: "$149",
    priceNote: "Pricing varies by vehicle size",
    description: "Perfect for regular maintenance and keeping your vehicle looking great between full details.",
    duration: "1.5–2.5 hours",
    idealFor: "Sedans & coupes needing a quick refresh",
    color: "from-zinc-800 to-zinc-700",
    features: [
      "Full exterior hand wash",
      "Interior vacuum (all areas)",
      "Interior wipe-down",
      "Dashboard & console cleaning",
      "Window cleaning (in & out)",
      "Tire cleaning & dressing",
      "Wheel cleaning",
      "Door jamb wipe-down",
    ],
  },
  {
    id: "premium",
    name: "Premium Package",
    tagline: "The Popular Choice",
    price: "$279",
    priceNote: "Most popular for sedan & SUV owners",
    description: "Our most popular option — a thorough inside-and-out detail that leaves your vehicle looking showroom-new.",
    duration: "3–5 hours",
    idealFor: "SUVs, trucks & families wanting a thorough clean",
    popular: true,
    color: "from-gold-600 to-gold-500",
    features: [
      "Everything in Basic Package",
      "Clay bar treatment",
      "Paint sealant application",
      "Hot water extraction (carpet & seats)",
      "Steam cleaning",
      "Leather cleaning & conditioning",
      "Engine bay cleaning",
      "Pet hair removal",
      "Odor treatment",
      "Plastic restoration",
    ],
  },
  {
    id: "deluxe",
    name: "Deluxe Package",
    tagline: "The Complete Experience",
    price: "$379",
    priceNote: "Best value for full decontamination",
    description: "The complete detailing experience with paint decontamination and ceramic protection.",
    duration: "5–7 hours",
    idealFor: "Vehicle enthusiasts wanting maximum protection",
    color: "from-blue-900 to-blue-800",
    features: [
      "Everything in Premium Package",
      "Paint decontamination (iron & clay)",
      "Ceramic spray protection",
      "Headliner cleaning",
      "Trunk detail",
      "Glass polishing",
      "Plastic trim restoration",
      "Ozone odor treatment",
      "Before & after photos",
    ],
  },
  {
    id: "ultimate",
    name: "Ultimate Package",
    tagline: "Concierge Perfection",
    price: "From $499",
    priceNote: "Price varies by vehicle condition & size",
    description: "The pinnacle of mobile detailing — a white-glove experience for those who accept nothing less than perfection.",
    duration: "6–8+ hours",
    idealFor: "Luxury & exotic vehicle owners",
    color: "from-purple-900 to-purple-800",
    features: [
      "Everything in Deluxe Package",
      "Comprehensive paint decontamination",
      "Full interior extraction & shampoo",
      "Leather deep clean & condition",
      "Ceramic spray coating (professional-grade)",
      "Engine bay detail",
      "All trim & plastic restoration",
      "Concierge scheduling priority",
      "Detailed condition report",
      "Complimentary follow-up wash",
    ],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Marcus T.",
    rating: 5,
    text: "I was blown away by the results. Irwinsito transformed my SUV — it looks better than the day I bought it. The convenience of mobile service is unbeatable. Scheduled online, they came to my driveway, done. 10/10.",
    date: "November 2024",
    service: "Full Detail",
    location: "Bluffton, SC",
    initials: "MT",
  },
  {
    id: "2",
    name: "Jennifer L.",
    rating: 5,
    text: "My car had dog hair everywhere — absolutely everywhere. After the pet hair removal and deep clean, I couldn't believe it was the same interior. Professional, thorough, and worth every penny.",
    date: "October 2024",
    service: "Premium Package",
    location: "Hilton Head, SC",
    initials: "JL",
  },
  {
    id: "3",
    name: "David R.",
    rating: 5,
    text: "As someone who drives a luxury vehicle, I'm very particular about who touches my car. GAutoDetailing exceeded every expectation. The ceramic spray made my paint look incredible. Highly recommend.",
    date: "December 2024",
    service: "Ultimate Package",
    location: "Hardeeville, SC",
    initials: "DR",
  },
  {
    id: "4",
    name: "Sarah M.",
    rating: 5,
    text: "The steam cleaning on my seats removed stains I thought were permanent. The attention to detail was impressive — they cleaned places I didn't even know needed cleaning. My car smells and looks brand new.",
    date: "October 2024",
    service: "Interior Detail",
    location: "Beaufort, SC",
    initials: "SM",
  },
  {
    id: "5",
    name: "Carlos V.",
    rating: 5,
    text: "I've tried other detailers in the area but none come close. The mobile service means I lose zero time out of my day. My truck gets the deluxe package every 3 months and it always looks incredible.",
    date: "November 2024",
    service: "Deluxe Package",
    location: "Bluffton, SC",
    initials: "CV",
  },
  {
    id: "6",
    name: "Amanda K.",
    rating: 5,
    text: "Got a full detail before selling my car and it increased my sale price by over $1,000. The buyer commented on how pristine the interior was. Best investment I made. Thank you GAutoDetailing!",
    date: "September 2024",
    service: "Full Detail",
    location: "Hilton Head, SC",
    initials: "AK",
  },
  {
    id: "7",
    name: "Robert H.",
    rating: 5,
    text: "The ceramic spray protection is amazing — water beads off my car like nothing I've seen. Six months later and it's still water-repellent. The whole detail process was smooth and the results speak for themselves.",
    date: "July 2024",
    service: "Ceramic Spray Protection",
    location: "Beaufort, SC",
    initials: "RH",
  },
  {
    id: "8",
    name: "Lisa P.",
    rating: 5,
    text: "Booked for my minivan after a road trip — it was chaos inside. They arrived on time, were professional throughout, and turned it from a disaster into something I was proud to drive again. Excellent service.",
    date: "August 2024",
    service: "Premium Package",
    location: "Hardeeville, SC",
    initials: "LP",
  },
];

export const FAQS: FAQItem[] = [
  {
    question: "What areas do you service?",
    answer: "We provide mobile auto detailing services throughout the South Carolina Lowcountry, including Hardeeville, Bluffton, Hilton Head Island, and Beaufort. We travel directly to your home, office, or wherever your vehicle is parked.",
    category: "General",
  },
  {
    question: "Do I need to bring my car anywhere?",
    answer: "Absolutely not — that's the beauty of mobile detailing! We come directly to you at your home, workplace, or any preferred location. All we need is access to your vehicle and a nearby water source (or we can bring our own).",
    category: "Service",
  },
  {
    question: "How long does a full detail take?",
    answer: "A full detail typically takes between 3–5 hours depending on the vehicle size, condition, and the specific services requested. Larger vehicles like SUVs and trucks may take longer. We'll give you a time estimate when you book.",
    category: "Service",
  },
  {
    question: "What's included in an exterior detail?",
    answer: "Our exterior detail includes a thorough hand wash, clay bar treatment (removes embedded contaminants), wheel and tire cleaning, tire dressing, door jamb cleaning, window cleaning, and a coat of protection (wax or sealant depending on the package).",
    category: "Services",
  },
  {
    question: "What's included in an interior detail?",
    answer: "Our interior detail covers deep vacuuming of all carpet and seats, dashboard and console cleaning, leather cleaning and conditioning, window cleaning from inside, cup holder and vent cleaning, stain treatment, and odor elimination.",
    category: "Services",
  },
  {
    question: "How is ceramic spray protection different from wax?",
    answer: "Ceramic spray protection creates a semi-permanent hydrophobic layer on your paint that repels water, dirt, and contaminants far better than wax. It typically lasts 3–6 months versus 4–6 weeks for wax. It also provides superior UV protection and gives a deeper, more reflective shine.",
    category: "Protection",
  },
  {
    question: "Do you remove pet hair?",
    answer: "Yes! Pet hair removal is one of our specialties. We use specialized rubber brushes and high-power extraction equipment to remove pet hair from carpet, seats, and crevices. Heavy pet hair may incur an additional fee, but we'll always be upfront about pricing before we begin.",
    category: "Interior",
  },
  {
    question: "Can you remove smoke odors from my vehicle?",
    answer: "Yes, we use ozone treatment and professional odor neutralizers to eliminate cigarette smoke and other embedded odors. For severe smoke odors, we combine steam cleaning with ozone treatment for best results. Multiple treatments may be needed for heavy smoking vehicles.",
    category: "Interior",
  },
  {
    question: "What's your pricing?",
    answer: "Our pricing starts at $59 for an express detail and ranges up to $499+ for our ultimate package. Price depends on vehicle size and condition. We offer transparent upfront pricing — no hidden fees. See our Pricing page for detailed package breakdowns.",
    category: "Pricing",
  },
  {
    question: "Do you charge extra for larger vehicles?",
    answer: "Yes, pricing is adjusted based on vehicle size. Compact cars and sedans are priced at our standard rates. SUVs, trucks, and minivans carry a small upcharge (typically $30–$75) depending on size and the services selected. We'll confirm pricing when you book.",
    category: "Pricing",
  },
  {
    question: "How do I book an appointment?",
    answer: "You can book through our website contact form, call or text us directly at (843) 555-0192, or send us a message on Instagram @ga_autodetailing7. We typically respond within a few hours and can often accommodate same-week appointments.",
    category: "Booking",
  },
  {
    question: "How far in advance should I book?",
    answer: "We recommend booking 2–3 days in advance, especially on weekends. However, we do our best to accommodate last-minute requests. For fleet services or multiple vehicles, please give us a week's notice.",
    category: "Booking",
  },
  {
    question: "What happens if it rains on my appointment day?",
    answer: "If rain is forecasted on your appointment day, we'll reach out to reschedule at a mutually convenient time at no charge. For interior-only services, light rain doesn't affect us. We monitor weather closely and always prioritize delivering quality results.",
    category: "Booking",
  },
  {
    question: "Do you need access to water and power?",
    answer: "For most services, a standard outdoor water spigot is all we need. We bring our own professional-grade hoses, soaps, tools, and equipment. If no water source is available, let us know in advance and we may be able to arrange alternatives.",
    category: "Service",
  },
  {
    question: "What products do you use?",
    answer: "We use only professional-grade, pH-balanced automotive products including premium soaps, conditioners, sealants, and protectants. We never use dish soap or off-the-shelf consumer products that can damage your vehicle's surfaces.",
    category: "Products",
  },
  {
    question: "Can you detail my luxury or exotic car?",
    answer: "Absolutely! We specialize in luxury and exotic vehicle detailing. We understand the unique requirements of high-end paint, leather, carbon fiber, and specialty materials. Our white-glove luxury service uses only the finest products safe for exotic finishes.",
    category: "Specialty",
  },
  {
    question: "Do you offer monthly maintenance plans?",
    answer: "Yes! We offer monthly maintenance programs perfect for keeping your vehicle in top condition year-round. Monthly clients enjoy priority scheduling, discounted rates, and a dedicated detailer who knows your vehicle. Contact us to discuss a custom plan.",
    category: "Plans",
  },
  {
    question: "Do you offer gift cards?",
    answer: "Yes! We offer gift cards in any amount — perfect for birthdays, holidays, or any special occasion. A professional detail makes an incredible gift for car enthusiasts and everyday drivers alike. Contact us to purchase a gift card.",
    category: "Gift Cards",
  },
  {
    question: "Do you detail motorcycles?",
    answer: "Yes! We offer motorcycle detailing covering frame, tank, chrome, wheels, and all trim. It's a meticulous process that brings out the best in your bike. Contact us for motorcycle-specific pricing.",
    category: "Specialty",
  },
  {
    question: "How do I prepare my car for a detail?",
    answer: "Remove personal belongings, trash, and any items you don't want us to move. That's it! You don't need to wash or clean anything beforehand — that's our job. Just make sure we have clear access to the vehicle on appointment day.",
    category: "General",
  },
  {
    question: "What payment methods do you accept?",
    answer: "We accept cash, Venmo, Zelle, CashApp, and all major credit and debit cards. Payment is due upon completion of the service. For larger packages, a deposit may be required at booking.",
    category: "Payment",
  },
  {
    question: "Is my vehicle safe while you're working on it?",
    answer: "Absolutely. We treat every vehicle as if it were our own. We're fully insured, use only paint-safe products, and employ proven techniques. We'll never use abrasive materials or methods that could harm your vehicle's surfaces.",
    category: "General",
  },
  {
    question: "Do you offer fleet services for businesses?",
    answer: "Yes! We work with businesses of all sizes to maintain fleet vehicles. Whether you have 2 or 20+ vehicles, we can create a custom fleet maintenance program with volume pricing and flexible scheduling. Contact us for a custom fleet quote.",
    category: "Fleet",
  },
];

export const SERVICE_AREAS: ServiceArea[] = [
  {
    name: "Hardeeville",
    slug: "hardeeville",
    state: "SC",
    description: "Professional mobile auto detailing serving Hardeeville, South Carolina",
    longDescription: "GAutoDetailing proudly serves Hardeeville, SC with premium mobile auto detailing. Whether you're near the Historic District, Argent Lakes, or anywhere in between, we bring showroom-quality results directly to your location.",
    keywords: [
      "mobile auto detailing hardeeville sc",
      "auto detailing hardeeville sc",
      "car detailing hardeeville sc",
      "interior detailing hardeeville",
      "exterior detailing hardeeville",
      "car wash hardeeville",
      "mobile car wash hardeeville",
      "vehicle detailing hardeeville",
    ],
    neighborhoods: ["Historic District", "Argent Lakes", "Riverton Pointe", "Sun City Hilton Head", "Tradition"],
    zipCodes: ["29927"],
  },
  {
    name: "Bluffton",
    slug: "bluffton",
    state: "SC",
    description: "Premium mobile auto detailing in Bluffton, South Carolina",
    longDescription: "GAutoDetailing serves the entire Bluffton area with professional mobile detailing. From Old Town Bluffton to Palmetto Bluff and every community in between, we bring elite-level detailing directly to you.",
    keywords: [
      "mobile auto detailing bluffton sc",
      "car detailing bluffton sc",
      "interior car cleaning bluffton",
      "exterior car cleaning bluffton",
      "mobile car wash bluffton",
      "mobile detailer bluffton",
      "auto detail bluffton",
      "best auto detailing bluffton",
    ],
    neighborhoods: ["Old Town Bluffton", "Palmetto Bluff", "Hampton Lake", "Berkeley Hall", "Belfair", "Rose Hill", "Colleton River"],
    zipCodes: ["29910", "29909"],
  },
  {
    name: "Hilton Head Island",
    slug: "hilton-head",
    state: "SC",
    description: "Luxury mobile auto detailing on Hilton Head Island, South Carolina",
    longDescription: "Hilton Head Island's premier mobile auto detailing service. Perfect for luxury vehicles, vacation rentals, and Hilton Head residents who demand the finest. We serve all of Hilton Head — from Sea Pines to Palmetto Dunes.",
    keywords: [
      "mobile auto detailing hilton head",
      "car detailing hilton head island",
      "auto detailing hilton head sc",
      "luxury car detailing hilton head",
      "mobile car wash hilton head",
      "interior detail hilton head",
      "exterior detail hilton head",
      "ceramic protection hilton head",
    ],
    neighborhoods: ["Sea Pines", "Palmetto Dunes", "Port Royal Plantation", "Shipyard Plantation", "Spanish Wells", "Wexford Plantation", "Indigo Run"],
    zipCodes: ["29928", "29926"],
  },
  {
    name: "Beaufort",
    slug: "beaufort",
    state: "SC",
    description: "Professional mobile auto detailing serving Beaufort, South Carolina",
    longDescription: "GAutoDetailing brings premium mobile auto detailing to Beaufort, SC. From the Historic District to Dataw Island and Port Royal, we deliver exceptional results wherever you are in the greater Beaufort area.",
    keywords: [
      "mobile auto detailing beaufort sc",
      "auto detailing beaufort sc",
      "car detailing beaufort",
      "interior detailing beaufort",
      "exterior detailing beaufort",
      "mobile car wash beaufort",
      "vehicle detailing beaufort",
      "best auto detailer beaufort",
    ],
    neighborhoods: ["Historic District", "Port Royal", "Dataw Island", "Mossy Oaks", "Lady's Island", "Saint Helena Island"],
    zipCodes: ["29902", "29906", "29907"],
  },
];

export const SERVICE_CATEGORIES = [
  { id: "packages", label: "Packages", icon: "Package" },
  { id: "exterior", label: "Exterior", icon: "Car" },
  { id: "interior", label: "Interior", icon: "Sofa" },
  { id: "wheel-tire", label: "Wheels & Tires", icon: "Circle" },
  { id: "protection", label: "Protection", icon: "Shield" },
  { id: "specialty", label: "Specialty", icon: "Star" },
];
